name: Hello 

on:
  push:
    branches: [master, main]     

jobs:

  greet:

    run-on:
    steps:
      - name: say hello users
        run: echo "Hello Dosto"

      - name: say hello username
        run: echo "Hello $USER"
